### ISSUE TITLE
oneOf works for only Email

### ISSUE THREAD

**Issue by efocoder** [vasilevich/feathers-hooks-yup#1]
I have tried the oneOf validator or email and it works fine.

But when I tried it on any other field like password confirmation, it doesn't work 

Any help?

**Comment by vasilevich** [comment]
Hello, I think your issue might be better answered if you provide a code example.
moreover I believe your issue is with the [Yup framework](https://github.com/jquense/yup) itself rather than feathers-hooks-yup which simpley pass your context into the [Yup framework](https://github.com/jquense/yup) as is, and makes a simple [true/false check.](https://github.com/vasilevich/feathers-hooks-yup/blob/master/ts/index.ts#L19)  by passing your object as is, and checking if there is an error.
I also suggest you to try your object on Yup directly as done in my code example
```

/** Put your own schema here **/
const yupSchemaObject =  yup.object().shape({    //<------------------ Your yup schema
  name: yup.string().required(),
  age: yup.number().required().positive().integer(),
  email: yup.string().email(),
  website: yup.string().url(),
  createdOn: yup.date().default(function () {
    return new Date();
  }),
});

const data={   /**  your data...  **/  };  // <-------------------Your  Object
yupSchemaObject.validate(data)
.then(success=>{ console.log(success); })
.catch(error=>{ console.log(error); });
```

let me know how it went.

**Comment by vasilevich** [comment]
I closed the issue due to inactivity,  I assume you somehow solved your problem, feel free to  reopen this, or new issue if you have not been helped.


have a good time and stay safe.
